/**
 * One-flag "just expose it" path for beta hosting: `WAR_PATROL_INTERNET=1`
 * auto-generates (and persists) an admin token when one wasn't set
 * explicitly, prints join-ready URLs on startup, and can optionally spawn a
 * `cloudflared` quick tunnel. This favors convenience for a small trusted
 * beta over hardening — see docs/internet-hosting.md for the tradeoffs.
 *
 * Pure LAN mode (no `WAR_PATROL_INTERNET`, no `WAR_PATROL_ADMIN_TOKEN`) is
 * completely unaffected: `resolveAdminToken()` returns `undefined` and
 * `printStartupBanner()` prints the exact same single line as before.
 */
import { randomBytes } from 'node:crypto';
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import { spawn } from 'node:child_process';
import { dataRoot } from './store/fileStore.js';

function truthyFlag(value: string | undefined): boolean {
  if (!value) return false;
  return !['0', 'false', 'no', 'off'].includes(value.trim().toLowerCase());
}

export function isInternetMode(): boolean {
  return truthyFlag(process.env.WAR_PATROL_INTERNET);
}

function adminTokenFile(): string {
  return path.join(dataRoot(), '.admin-token');
}

/**
 * Resolve the admin token for this run.
 *
 * - `WAR_PATROL_ADMIN_TOKEN` explicitly set: use it as-is (unchanged from #121).
 * - Unset, but `WAR_PATROL_INTERNET` is on: generate a token (or reuse the one
 *   persisted from a previous run at `data/.admin-token`) and write it back
 *   into `process.env.WAR_PATROL_ADMIN_TOKEN` so the existing `requireAdmin()`
 *   gate in `routes/api.ts` picks it up with no further changes.
 * - Neither set: no-op, returns `undefined` — identical to pre-existing LAN behavior.
 */
export function resolveAdminToken(): { token: string | undefined; autoGenerated: boolean } {
  const explicit = process.env.WAR_PATROL_ADMIN_TOKEN?.trim();
  if (explicit) {
    return { token: explicit, autoGenerated: false };
  }
  if (!isInternetMode()) {
    return { token: undefined, autoGenerated: false };
  }

  const file = adminTokenFile();
  let token: string | undefined;
  try {
    const existing = existsSync(file) ? readFileSync(file, 'utf8').trim() : '';
    if (existing) {
      token = existing;
    } else {
      token = randomBytes(24).toString('hex');
      writeFileSync(file, token, { mode: 0o600 });
    }
  } catch {
    // Disk unavailable (read-only fs, some containers) — fall back to a
    // per-process token. Still gets wired into the printed join URL below,
    // it just won't survive a restart.
    token = randomBytes(24).toString('hex');
  }
  process.env.WAR_PATROL_ADMIN_TOKEN = token;
  return { token, autoGenerated: true };
}

function localIPv4Addresses(): string[] {
  const nets = os.networkInterfaces();
  const addrs: string[] = [];
  for (const iface of Object.values(nets)) {
    for (const net of iface ?? []) {
      if (net.family === 'IPv4' && !net.internal) addrs.push(net.address);
    }
  }
  return addrs;
}

/**
 * Prints the same single line as before when there's no admin token (plain
 * LAN default). When a token is set (explicit or auto-generated), also
 * prints join-ready URLs with the token pre-filled as `?admin=<token>` so
 * the host can open one link and skip pasting the token into the UI.
 */
export function printStartupBanner(opts: {
  host: string;
  port: number;
  token: string | undefined;
  autoGenerated: boolean;
}): void {
  const { host, port, token, autoGenerated } = opts;
  console.log(`War Patrol server listening on http://${host}:${port}`);
  if (!token) return;

  const displayHosts =
    host === '0.0.0.0' || host === '::' ? ['127.0.0.1', ...localIPv4Addresses()] : [host];
  const adminQuery = `?admin=${token}`;

  console.log('');
  console.log(
    autoGenerated
      ? `Admin token (auto-generated, persisted at ${adminTokenFile()}):`
      : 'Admin token (from WAR_PATROL_ADMIN_TOKEN):',
  );
  console.log(`  ${token}`);
  console.log('');
  console.log('Open one of these to land already signed in as admin (skips pasting the token):');
  for (const h of displayHosts) {
    console.log(`  http://${h}:${port}/${adminQuery}`);
  }
  if (isInternetMode()) {
    console.log('');
    console.log(
      'WAR_PATROL_INTERNET is on: host/disk admin routes require this token, CORS still',
    );
    console.log(
      'reflects any Origin unless WAR_PATROL_CORS_ORIGIN is set, and the token above is',
    );
    console.log(
      'plaintext in this URL — put HTTPS in front (reverse proxy or WAR_PATROL_TUNNEL=',
    );
    console.log('cloudflared) before sharing a link beyond this machine. See docs.');
  }
  console.log('');
}

const CLOUDFLARED_QUICK_TUNNEL_URL = /https:\/\/[a-zA-Z0-9-]+\.trycloudflare\.com/;

/**
 * Optional one-command tunnel: `WAR_PATROL_TUNNEL=cloudflared` spawns
 * `cloudflared tunnel --url http://localhost:<port>` (must already be
 * installed — no new dependency added to this repo) and prints the public
 * HTTPS URL it allocates, plus a join-ready link with the admin token
 * pre-filled. No-op unless the var is set; failures are logged, never fatal.
 */
export function maybeStartTunnel(port: number): void {
  const mode = process.env.WAR_PATROL_TUNNEL?.trim().toLowerCase();
  if (!mode || !truthyFlag(mode)) return;
  if (mode !== 'cloudflared' && mode !== '1' && mode !== 'true') {
    console.log(
      `[war-patrol] Unknown WAR_PATROL_TUNNEL=${mode} (supported: "cloudflared"). Skipping tunnel.`,
    );
    return;
  }

  console.log('[war-patrol] Starting cloudflared quick tunnel...');
  let child: ReturnType<typeof spawn>;
  try {
    child = spawn('cloudflared', ['tunnel', '--url', `http://localhost:${port}`], {
      stdio: ['ignore', 'pipe', 'pipe'],
    });
  } catch (err) {
    console.log(`[war-patrol] Could not start cloudflared: ${(err as Error).message}`);
    return;
  }

  let printed = false;
  const onData = (buf: Buffer) => {
    if (printed) return;
    const match = buf.toString().match(CLOUDFLARED_QUICK_TUNNEL_URL);
    if (match) {
      printed = true;
      const token = process.env.WAR_PATROL_ADMIN_TOKEN;
      console.log('');
      console.log(`[war-patrol] Public tunnel URL: ${match[0]}`);
      if (token) {
        console.log(`[war-patrol] Join-ready (admin):  ${match[0]}/?admin=${token}`);
      }
      console.log(
        '[war-patrol] Quick tunnels are unauthenticated and anyone with the URL can reach',
      );
      console.log(
        '[war-patrol] this server — fine for a short beta window, not for long-term hosting.',
      );
      console.log('');
    }
  };
  child.stdout?.on('data', onData);
  child.stderr?.on('data', onData);
  child.on('error', (err) => {
    if ((err as NodeJS.ErrnoException).code === 'ENOENT') {
      console.log('[war-patrol] cloudflared not found on PATH. Install it, then re-run:');
      console.log(
        '[war-patrol]   https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/downloads/',
      );
    } else {
      console.log(`[war-patrol] cloudflared error: ${err.message}`);
    }
  });
  child.on('exit', (code) => {
    if (code !== 0 && code !== null) {
      console.log(`[war-patrol] cloudflared exited with code ${code}`);
    }
  });
  process.once('exit', () => {
    try {
      child.kill();
    } catch {
      /* best effort */
    }
  });
}
