import { buildApp } from './app.js';
import { maybeStartTunnel, printStartupBanner, resolveAdminToken } from './hostInfo.js';

const port = Number(process.env.PORT ?? 8787);
const host = process.env.HOST ?? '0.0.0.0';

// See docs/internet-hosting.md — `WAR_PATROL_INTERNET=1` auto-generates/persists
// an admin token when `WAR_PATROL_ADMIN_TOKEN` isn't set explicitly. No-op
// (returns undefined) for plain LAN parties, matching pre-existing behavior.
const { token, autoGenerated } = resolveAdminToken();

const app = await buildApp();
await app.listen({ port, host });
printStartupBanner({ host, port, token, autoGenerated });
maybeStartTunnel(port);
